version: "3.9"

services:
  backend:
    build:
      context: ..
      dockerfile: infrastructure/docker/backend.dockerfile
    ports:
      - "8000:8000"
    container_name: easyg-server

  frontend:
    build:
      context: ..
      dockerfile: infrastructure/docker/frontend.dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    container_name: easyg-web